import type { Metadata } from "next"
import "./globals.css"

// components
import Header from "@/components/header"

export const metadata: Metadata = {
  title: "Only Devs",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="bg-white overflow-x-hidden flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  )
}
